export const rejectionReasonCodes = [
  'UNSUPPORTED_SPORT',
  'UNSUPPORTED_COMPETITION',
  'UNSUPPORTED_EVENT_TYPE',
  'NON_BINARY_MARKET',
  'MISSING_CONDITION_ID',
  'MISSING_QUESTION_ID',
  'MISSING_RULES',
  'NEGATIVE_RISK_UNSUPPORTED',
  'MARKET_INACTIVE',
  'MARKET_ARCHIVED',
  'NEAR_EXPIRY',
  'AMBIGUOUS_RESOLUTION',
  'ODDS_OR_PROBABILITY_RESULT',
  'DISALLOWED_FOOTBALL_MARKET_TYPE',
  'DISALLOWED_TENNIS_MARKET_TYPE',
  'ATP_250_PLUS_UNSUPPORTED',
  'DISALLOWED_UFC_MARKET_TYPE',
  'DISALLOWED_F1_MARKET_TYPE',
  'CONDITION_RESOLVED',
  'INVALID_LOSER_FEE_BPS',
] as const;

export type RejectionReasonCode = typeof rejectionReasonCodes[number];
